# Ubuntu 15.04 with Java 8 installed
 
FROM adoptopenjdk:8-jdk-hotspot
RUN apt-get update && \
	apt-get install unzip && \
    apt-get clean
	
ADD build/distributions/ExchangeAccountDataWorker-1.0.zip .
RUN unzip -q ExchangeAccountDataWorker-1.0.zip && \
    rm ExchangeAccountDataWorker-1.0.zip && \
    mv ExchangeAccountDataWorker-* ExchangeAccountDataWorker && \
    chmod +x ExchangeAccountDataWorker/bin/ExchangeAccountDataWorker && \
    sed -i -e 's/\r$//' ExchangeAccountDataWorker/bin/ExchangeAccountDataWorker

ENTRYPOINT ["/ExchangeAccountDataWorker/bin/ExchangeAccountDataWorker"]
CMD ["--console"]